### ISSUE TITLE
Eclipse reader plugin fails in both ParaView 4.2.4 and 5.1 (the latest) versions

### ISSUE THREAD

**Issue by AsoAgile** [jbrezmorf/pareview#1]
Dear Jan,

I am trying to use your Eclipse-reader plug in for ParaView to visualize Eclipse output data (*.egrid and *.unrst), but it fails with the following error, after I press apply button (I followed your readme.MT file). I tried my own files and even your test.egrid and test.unrst  files but both fail as follow and I cannot visualize the data. I appreciate if you could have a look at the issue.

Regards,
AsoAgile

== Eclipse Reader Exception ==
Exception:  <type 'exceptions.TypeError'> only length-1 arrays can be converted to Python scalars
  File "<string>", line 992, in RequestData
  File "<string>", line 500, in read_egrid
  File "<string>", line 463, in read_dict
  File "<string>", line 450, in make_dict
Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "<string>", line 10, in RequestData
  File "<string>", line 1128, in RequestData
AttributeError: EclipseIO instance has no attribute 'output'

**Comment by AsoAgile** [comment]
It was to do with my numpy version. I added 'new_value.astype(array_type)' to vector types (i.e. when  'not vector_size is None') 'make_dict' function and solved the issue.

**Comment by mlelous** [comment]
Hi AsoAgile, 

I'm interested in solving the same issue as you were facing while importing "test.unrst". Unfortunately, I do not understand the way you fixed this problem. Could you help me on that very subject ?
Thank you.
